### ISSUE TITLE
Cd'ing into directories broken

### ISSUE THREAD

**Issue by dgarzon** [jethrokuan/fzf#81]
While running the `Alt-o` or `Alt-Shift-o` I keep getting the following errors:
```
❯  Pictures
fish: Unknown command 'Pictures'
fish:
 Pictures
 ^

❯  Developer/repo
fish: The file 'Developer/repo' is not executable by this user
 Developer/repo
 ^
```

These are the versions for `fish`, `fzf` and `fisher` I am running on:
```
❯ fish --version
fish, version 2.7.1

❯ fzf --version
0.17.4 (brew)

❯ fisher --version
fisherman version 2.13.3 ~/.config/fish/functions/fisher.fish
```

Is there anything I can do to fix the aforementioned problem? Thank you in advanced!

**Comment by jethrokuan** [comment]
Possibly resolved with #82, could you pull in the latest changes and try again? `fisher u jethrokuan/fzf`

**Comment by dgarzon** [comment]
Just pulled, started a new session, and still see the same results! Thank you for taking the time into looking at this 👍

**Comment by jethrokuan** [comment]
Can I get your output of the following?

```
echo $FZF_CD_COMMAND
echo $FZF_CD_OPTS
echo $FZF_DEFAULT_OPTS
```

**Comment by dgarzon** [comment]
Sure!
```
❯ echo $FZF_CD_COMMAND

```
```
❯ echo $FZF_CD_OPTS

```
```
❯ echo $FZF_DEFAULT_OPTS
--height 40%
```

**Comment by jethrokuan** [comment]
hmm that's strange, all of your configuration is equivalent to mine, and i'm not getting your issue. My guess now is that some other plugin is interfering with this one. Can I check if you have any other plugins installed? You can show me the contents of your `fishfile`, as well as `config.fish`.

**Comment by dgarzon** [comment]
Of course:
```
~/.config/fish
❯ cat fishfile
fisherman/await
edc/bass
fisherman/fnm
fisherman/fzf
fisherman/get_file_age
jhillyerd/plugin-git
fisherman/last_job_id
fisherman/menu
rafaelrinaldi/pure
tuvistavie/fish-ssh-agent
oh-my-fish/plugin-thefuck
fisherman/z
```
```
~/.config/fish
❯ cat config.fish
set -u MAVEN_OPTS "-Xmx4G"
set -u SBT_OPTS "-Xmx4096m -Xss512m"
set -u DIRENV_LOG_FORMAT ""

set -gx PATH ~/.local/bin $PATH

eval (direnv hook fish)
```

**Comment by jethrokuan** [comment]
made a mistake in my earlier PR which was now fixed, can you try again?
